### ISSUE TITLE
Support dependencies to multiple gems

### ISSUE THREAD

**Issue by tdeo** [pre-commit/pre-commit-mirror-maker#20]
This would probably be quite a headache to handle, but it would be super nice to create a mirror having 2 (or n) dependencies by running `pre-commit-mirror path-to-mirror ruby gem1,gem2 '\.rb'` for example.

The use case I came across is using `rubocop-rspec` with `rubocop`. It basically consists in running rubocop with `--require rubocop-rspec` but needs to have the `rubocop-rspec` gem installed as well.

Right now I manage to get some work around by first generating the mirror, then adding the dependency to the second gem as a new commit and then rewrite the commit history order to move that commit to the beginning. But the process breaks the tags with are not in the master branch anymore, is quite painful, and doesn't work if we want to be able to select a "matrix" of versions.

Do you think it's worth investigating further?

**Comment by asottile** [comment]
Yeah I think something like that could happen.  I don't know how the tags would properly work out.

One design I thought of would be to keep the extra dependencies at always a specific version or something?

Maybe a cli like:

```
pre-commit-mirror path-to-mirror ruby gem1 --additional-deps gem2
```

?

**Comment by tdeo** [comment]
Could be a good option, maybe by specifying `--additional-dep dependency-gem,1.2.3` to get a fixed version? And option could be used several times?

**Comment by asottile** [comment]
Yeah, I'd use the existing syntax (whatever it is per language) and avoid parsing the cmdline argument (and `action='append'` for multiple uses of that argument)

**Comment by tdeo** [comment]
Actually I have a PR almost ready. Using the language's syntax wouldn't be really convenient for ruby I think because the format is `'name', 'version'`. Which is not super convenient in command line arguments because of the space and quotes.

**Comment by asottile** [comment]
The ruby syntax we've been using with sucesss is `package:version`

For example:

```yaml
        additional_dependencies: ['puppet-lint:1.1.0']
```

**Comment by tdeo** [comment]
I wasn't aware that syntax was directly available for ruby. Because what I add in mind is adding an extra line in the `.gemspec` file. Because this works directly, there's actually no need to configure the mirror with extra dependencies, it can be added directly in the `.pre-commit-config.yaml` of any repo in the first place.

**Comment by asottile** [comment]
Indeed! Is this feature still a good idea then?

**Comment by tdeo** [comment]
Indeed, this feature is useless thanks to the `additional_dependencies`.

But that also got me thinking that the creation of mirrors can be avoided. I just tried making an empty repo for a gem hook for example, and it turns out creating a fake gem without any dependency (like https://github.com/pricematch/pre-commit-hook-ruby) can then be reused for any gem at any version without having to create mirrors.

For example, using this repo, I can add in a `.pre-commit-config.yaml` the following hook:
```yaml
-   repo: git://github.com/pricematch/pre-commit-hook-ruby.git
    sha: b11b6d99d8b3fb3e46e8b06f716fbcf5db2433ff
    hooks:
    -   id: ruby
        additional_dependencies:
        - rubocop:0.43.0
        - rubocop-rspec:1.7.0
        entry: rubocop
        files: \.(rb|rake)$
        args:
        - -a
        - --require
        - rubocop-rspec
        - --config=config/rubocop/rubocop.yml
```
And then I'll also be able to change any versions without having to manipulate the mirror.

How are you feeling about this strategy?
