### ISSUE TITLE
Quoted 'types' key

### ISSUE THREAD

**Issue by lcnittl** [pre-commit/pre-commit-mirror-maker#61]
When using `pre-commit-mirror-maker` to mirror a repository:

```
$ git init mirrors-CleverCSV
$ pre-commit-mirror mirrors-CleverCSV --language python --package-name clevercsv --entry "clevercsv standardize --in-place" --types csv
```

 the resulting `.pre-commit-hooks.yaml` file has its `types` key single quoted:

```yaml
-   id: clevercsv standardize --in-place
    name: clevercsv
    entry: clevercsv standardize --in-place
    language: python
    'types': [csv]
    args: []
    require_serial: false
    additional_dependencies: []
```

**Comment by asottile** [comment]
doesn't matter, both are valid yaml

**Comment by lcnittl** [comment]
Yes indeed, was just my OCD 😄 (and the fact that it seems it would just require to remove the quotes here)

https://github.com/pre-commit/pre-commit-mirror-maker/blob/aea1d0ff0765295f779cc2e8dc5a43d05bcb3887/pre_commit_mirror_maker/all/.pre-commit-hooks.yaml#L5

**Comment by asottile** [comment]
if you try and remove the quotes there you'll see why I did it ;)

**Comment by asottile** [comment]
plus I find it mildly amusing to see who [copy pastes](https://github.com/myint/autoflake/blob/d43d8a770c0f9ef2f68b368670ab882f6ca6ea03/.pre-commit-hooks.yaml#L5) out of the mirror repos -- in a way it's a harmless marker

**Comment by lcnittl** [comment]
> if you try and remove the quotes there you'll see why I did it ;)

I tested with types and files, and think that the output is – except for the quotes of course – the same in both cases, respectively. But maybe I am missing something -- or am not testing a specific use case.

Without quotes:
```yaml
-   id: clevercsv standardize
    name: clevercsv
    entry: clevercsv standardize
    language: python
    types: [csv]
    args: ["--in-place"]
    require_serial: false
    pass_filenames: false
    additional_dependencies: []
```

With quotes (master branch):
```yaml
-   id: clevercsv standardize
    name: clevercsv
    entry: clevercsv standardize
    language: python
    'types': [csv]
    args: ["--in-place"]
    require_serial: false
    pass_filenames: false
    additional_dependencies: []
```

I was just too curious.


> plus I find it mildly amusing to see who [copy pastes](https://github.com/myint/autoflake/blob/d43d8a770c0f9ef2f68b368670ab882f6ca6ea03/.pre-commit-hooks.yaml#L5) out of the mirror repos -- in a way it's a harmless marker

Well, who could say something against this then 🤣🤣
